import { execSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";

const repoRoot = resolve(__dirname, "..");
const fixturesDir = resolve(__dirname, "fixtures");

// Scan the fixtures directory to identify each test case (one per folder)
const fixtures = readdirSync(fixturesDir, { withFileTypes: true })
  .filter((dirent) => dirent.isDirectory())
  .map((dirent) => dirent.name);

describe("VDL Plugin TS e2e", () => {
  // Ensure the plugin is built before running the end-to-end tests
  beforeAll(() => {
    execSync("npm run build", { cwd: repoRoot, stdio: "pipe" });
  });

  it.each(fixtures)("compiles fixture: %s", (fixtureName) => {
    const fixturePath = join(fixturesDir, fixtureName);
    const outDir = join(fixturePath, "gen");
    const mainPath = join(fixturePath, "main.ts");

    // Run the VDL compiler using the local plugin to generate TypeScript code
    execSync("npx vdl generate", { cwd: fixturePath, stdio: "pipe" });

    const generatedFiles = readdirSync(outDir)
      .filter((file) => file.endsWith(".ts"))
      .sort();

    expect(generatedFiles.length).toBeGreaterThan(0);

    for (const file of generatedFiles) {
      // Read the generated file and skip the first 3 lines (autogenerated header)
      // to ensure snapshots remain stable across runs.
      const content = readFileSync(join(outDir, file), "utf-8")
        .trim()
        .split("\n")
        .slice(3)
        .join("\n")
        .trim();
      expect(content).toMatchSnapshot(file);
    }

    // If a main.ts file exists in the fixture, execute it to perform runtime assertions
    if (existsSync(mainPath)) {
      execSync("node main.ts", { cwd: fixturePath, stdio: "inherit" });
    }
  });
});
