import { newGenerator } from "@varavel/gen";
import * as strings from "@varavel/vdl-plugin-sdk/utils/strings";

/**
 * Wraps a generated TypeScript module body with stable whitespace handling.
 */
export function renderTypeScriptFile(body: string): string {
  const g = newGenerator().withSpaces(2);
  const trimmedBody = body.trim();

  g.line("/* eslint-disable */");
  g.line("/* tslint:disable */");
  g.line("// biome-ignore-all lint: Generated by VDL");
  g.break();

  if (trimmedBody.length > 0) {
    g.raw(trimmedBody);
    g.break();
  }

  return strings.limitBlankLines(g.toString(), 1);
}
